### ISSUE TITLE
1.19.2 Crate Delight and Storage Delight together result in error on launch

### ISSUE THREAD

**Issue by CattsyTheKitty** [axperty/cratedelight-forge#1]
I'm using Forge ver. 43.3.9, Farmer's Delight ver. 1.2.4 and newest releases of Crate Delight (1.0.5) and Storage Delight (1.0.1) for 1.19.2. 
When I try to start Minecraft from launcher using both CD and SD, the game fails to launch and launcher shows the pop-up with info about error n. 1. I don't get any crash report, only log that I attached. 
I don't have any issue with only Farmer's Delight and CD, or only FD and SD. There's no issue with adding More Delight to the mix.
[latest.log](https://github.com/axperty/cratedelight-forge/files/14749162/latest.log)

**Comment by axperty** [comment]
Hi CattsyTheKitty,

I'll look into this error and give you a solution as soon as possible.

Have a good day,
- Axperty

**Comment by CattsyTheKitty** [comment]
Wow, that was quick! Thanks for addressing the issue, I'll wait for updates!

**Comment by axperty** [comment]
The update has been released, now you can play with Crate Delight and Storage Delight without any problems, download them here, or just click _"Update"_ on the launcher you play:

[Download on CurseForge](https://www.curseforge.com/minecraft/mc-mods/storage-delight-forge/files/5211383) | [Download on Modrinth](https://modrinth.com/mod/storage-delight/version/cQxtYhdb)

Thank you so much for reporting this bug! Don't forget you can also join my [Discord server](https://discord.gg/GuURSDAmmQ) for updates.

**Comment by CattsyTheKitty** [comment]
Downloaded, tested and works like a charm! Thank you!
