### ISSUE TITLE
Feature: Support for vanilla crates/bags when Farmer's Delight not used?

### ISSUE THREAD

**Issue by kingstairs** [axperty/cratedelight-forge#13]
Since this mod does not have a dependency on Farmer's Delight (FD), it would be nice to have vanilla crates/bags (potatoes, carrots, etc.), that FD provides, added/enabled when FD is not used.
Thank you.

**Comment by axperty** [comment]
Hi kingstairs,

This is already a feature which you can try. If you disable Farmer's Delight those crates you have mentioned will be available to craft.

If you have any questions, feel free to ask.

Have a good day,
Axperty.
