### ISSUE TITLE
No data fixer for rotten_tomato and handcrafted

### ISSUE THREAD

**Issue by Shadowblitz16** [axperty/cratedelight-forge#15]
```
[13:39:42] [Render thread/ERROR]: No data fixer registered for rotten_tomato
[13:39:43] [Render thread/ERROR]: No data fixer registered for handcrafted
```
https://mclo.gs/w6RZwet

**Comment by axperty** [comment]
Hi Shadowblitz16,

This is error is related to Farmer's Delight (Forge or Fabric), there's no need to worry about it, and the game will work as usual.

Have a good day,
Axperty.

**Comment by Shadowblitz16** [comment]
@axperty yes I know but it would be nice to get rid of the warnings.

**Comment by axperty** [comment]
Unfortunately, I can't make Crate Delight disable external errors from other mods, you could ask the authors of Farmer's Delight, vectorwing or MehVahdJukaar.

**Comment by Shadowblitz16** [comment]
> Unfortunately, I can't make Crate Delight disable external errors from other mods, you could ask the authors of Farmer's Delight, vectorwing or MehVahdJukaar.

ok I will ask. thankyou.
