### ISSUE TITLE
BUG: duplicated carrot crate recipe

### ISSUE THREAD

**Issue by Aruman-Zen** [axperty/cratedelight-forge#17]
farmer's delight already has one so maybe this isn't intended and should be removed
![image](https://github.com/user-attachments/assets/73ebef03-6d43-4a3d-a77a-ab4c6936ae91)

**Comment by axperty** [comment]
Hi Aruman-Zen,

That's not supposed to happen, as I made Crate Delight prioritize Farmer's Delight recipes if it's installed, what version and loader are you playing on?

**Comment by Aruman-Zen** [comment]
i'm playing on minecraft 1.21.1 FABRIC Loader 0.16.9
Using farmer's delight refabricated (which may be the the reason)
https://modrinth.com/mod/farmers-delight-refabricated

**Comment by axperty** [comment]
Thanks for the information, I'll take a look and release an update as soon as possible.

**Comment by axperty** [comment]
Hi Aruman-Zen,

An update has been just released fixing this, thank you so much for reporting this issue.

Have a good day,
Axperty.
