### ISSUE TITLE
Create's Wheat Flour Bag is generating in structures even though Create is not installed

### ISSUE THREAD

**Issue by Leichenengel** [axperty/cratedelight-forge#19]
Hello :)

I just noticed a bug which I'm not sure of, if it's caused by your mod, or the mod that generates the structure. The structure I found the wheat bags in was generated by Dungeon Delight. So since I don't have Create installed, should the wheat flour bag of your mod be generated at all? Is it a bug on your end or do I need to contact the dev of the Dungeon Delight Mod?

Cheers!

Leichenengel

**Comment by axperty** [comment]
Hi Leichenengel,

Crate Delight only adds the Wheat Flour Bag only when Create is loaded. It doesn't make any changes to structures. This means that it might be a bug from Dungeon Delight.

If you have any other questions, please let me know.

Have a good day,
Axperty.

**Comment by Leichenengel** [comment]
Alright, then I will report it to the Dungeon Delight Mod Owner :)
