### ISSUE TITLE
Wheat Flour Bag does not have a recipe and cannot be uncrafted into flour

### ISSUE THREAD

**Issue by Rayxanber** [axperty/cratedelight-forge#7]
Using the 7-12 update in 1.20.1, Create and Farmer's Delight are installed, perhaps they're conflicting?

**Comment by axperty** [comment]
Hi Rayxanber,

I'll take a look into this, thank you for letting me know.

Have a good day,
Axperty.

**Comment by axperty** [comment]
Hi Rayxanber,

I just issued an update fixing this bug, thank you so much for reporting this.

Have a good day,
Axperty.
